#!/usr/bin/env python3
"""HLM-v9 Chat Interface.

Interactive chat for the byte-level HLM-v9 Multiscale model.
This is a byte-level model (vocab=256), not token-based.

Usage:
    python geoformer/chat_hlm_v9.py --checkpoint "D:/Downloads/hlm_v9_step5000.pt"
    python geoformer/chat_hlm_v9.py --checkpoint "D:/Downloads/hlm_v9_step5000.pt" --port 7860
"""

import sys
import json
import argparse
import logging
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F_func

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from flask import Flask, Response, request, jsonify

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("chat-hlm-v9")

# ── Globals ──────────────────────────────────────────────────────────────
MODEL = None
CONFIG = None
DEVICE = None
STEP = None

BLADE_SEMANTIC = [
    "temporal", "narrative", "causation", "affect",
    "wisdom", "ecology", "relations", "epistemics"
]


# ── Import model code from the extracted notebook ────────────────────────
# We import the classes directly from the extracted file

def _import_hlm_v9():
    """Import HLM-v9 model classes."""
    import importlib.util
    model_path = Path(__file__).parent / "hlm_v9_model_raw.py"
    spec = importlib.util.spec_from_file_location("hlm_v9_model_raw", model_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_hlm_v9_mod = None

def get_hlm_v9_module():
    global _hlm_v9_mod
    if _hlm_v9_mod is None:
        _hlm_v9_mod = _import_hlm_v9()
    return _hlm_v9_mod


# ── Model loading ────────────────────────────────────────────────────────

def load_model(checkpoint_path: str, device: str):
    """Load HLM-v9 from checkpoint."""
    log.info(f"Loading checkpoint: {checkpoint_path}")
    ckpt = torch.load(checkpoint_path, map_location=device, weights_only=False)

    config = ckpt["config"]
    log.info(f"  Config: {config}")

    mod = get_hlm_v9_module()
    HLMv9 = mod.HLMv9

    model = HLMv9(
        grid_size=config.get("G", 4),
        n_tracks=config.get("T", 8),
        n_passes=config.get("P", 2),
        n_blocks=config.get("blocks", 24),
        mlp_hidden=config.get("H", 4096),
    )
    model.use_checkpoint = False  # No gradient checkpointing at inference

    state_dict = ckpt["model"]
    # Strip _orig_mod. prefix (from torch.compile)
    cleaned = {k.replace("_orig_mod.", ""): v for k, v in state_dict.items()}
    missing, unexpected = model.load_state_dict(cleaned, strict=False)
    if missing:
        log.warning(f"  Missing keys ({len(missing)}): {missing[:5]}...")
    if unexpected:
        log.warning(f"  Unexpected keys ({len(unexpected)}): {unexpected[:5]}...")

    model.to(device)
    model.eval()

    step = ckpt.get("step", "unknown")
    total_bytes = ckpt.get("total_bytes", 0)
    loss = ckpt.get("loss", 0)
    n_params = sum(p.numel() for p in model.parameters())
    log.info(f"  Loaded step {step}, {n_params:,} params, loss={loss:.4f}")
    log.info(f"  Total training bytes: {total_bytes:,}")
    return model, config, step


# ── Byte-level generation ────────────────────────────────────────────────

@torch.no_grad()
def generate_stream(
    prompt: str,
    max_new_bytes: int = 512,
    temperature: float = 0.8,
    top_k: int = 40,
    top_p: float = 0.9,
    repetition_penalty: float = 1.1,
):
    """Yield decoded text chunks as they're generated byte-by-byte."""
    # Encode prompt to raw UTF-8 bytes
    prompt_bytes = list(prompt.encode("utf-8"))
    byte_seq = prompt_bytes[:]
    max_seq = MODEL.max_seq_len  # 512

    generated_bytes = []
    pending_bytes = bytearray()  # Buffer for incomplete UTF-8 sequences

    for _ in range(max_new_bytes):
        # Crop to context window
        ctx = byte_seq[-max_seq:]
        input_tensor = torch.tensor([ctx], dtype=torch.long, device=DEVICE)

        outputs = MODEL(input_tensor)
        logits = outputs["logits"][:, -1, :]  # (1, 256)

        # Repetition penalty on recent bytes
        if repetition_penalty != 1.0 and generated_bytes:
            for prev_byte in set(generated_bytes[-64:]):
                if logits[0, prev_byte] > 0:
                    logits[0, prev_byte] /= repetition_penalty
                else:
                    logits[0, prev_byte] *= repetition_penalty

        if temperature == 0:
            next_byte = logits.argmax(dim=-1).item()
        else:
            logits = logits / temperature

            if top_k > 0:
                v, _ = torch.topk(logits, min(top_k, 256))
                logits[logits < v[:, [-1]]] = float("-inf")

            if top_p < 1.0:
                sorted_logits, sorted_indices = torch.sort(logits, descending=True)
                cum_probs = torch.cumsum(F_func.softmax(sorted_logits, dim=-1), dim=-1)
                remove = cum_probs > top_p
                remove[:, 1:] = remove[:, :-1].clone()
                remove[:, 0] = False
                indices_to_remove = remove.scatter(1, sorted_indices, remove)
                logits[indices_to_remove] = float("-inf")

            probs = F_func.softmax(logits, dim=-1)
            next_byte = torch.multinomial(probs, num_samples=1).item()

        generated_bytes.append(next_byte)
        byte_seq.append(next_byte)

        # Try to decode pending bytes + new byte as UTF-8
        pending_bytes.append(next_byte)
        try:
            text_chunk = pending_bytes.decode("utf-8")
            pending_bytes.clear()

            # Get blade profile periodically (every ~64 bytes to avoid slowdown)
            blades = None
            if len(generated_bytes) % 64 == 0 or len(generated_bytes) == 1:
                ctx_tensor = torch.tensor([byte_seq[-max_seq:]], dtype=torch.long, device=DEVICE)
                blades = get_blade_profile(ctx_tensor)

            yield text_chunk, blades
        except UnicodeDecodeError:
            # Incomplete multi-byte sequence, keep buffering
            if len(pending_bytes) > 4:
                # Corrupted — flush as replacement char
                pending_bytes.clear()
                yield "\ufffd", None

    # Flush any remaining bytes
    if pending_bytes:
        try:
            yield pending_bytes.decode("utf-8", errors="replace"), None
        except Exception:
            pass


@torch.no_grad()
def get_blade_profile(byte_seq_tensor):
    """Extract blade activation profile by hooking into the model's final hidden state.

    Runs a forward pass and applies the blade_classifier to the last position.
    """
    try:
        # We need the hidden state before output_head.
        # Use a forward hook on final_norm to capture it.
        hidden = {}

        def hook_fn(module, input, output):
            hidden["h"] = output

        handle = MODEL.final_norm.register_forward_hook(hook_fn)
        MODEL(byte_seq_tensor)
        handle.remove()

        if "h" in hidden:
            h = hidden["h"][:, -1, :]  # (1, d_model)
            blade_logits = MODEL.blade_classifier(h)  # (1, 8)
            blade_probs = F_func.softmax(blade_logits, dim=-1)
            return blade_probs[0].cpu().tolist()
        return None
    except Exception as e:
        log.debug(f"Blade profile error: {e}")
        return None


# ── Flask App ────────────────────────────────────────────────────────────

app = Flask(__name__)

HTML_PAGE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HLM-v9 Chat</title>
<style>
  :root {
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #e6edf3; --text-dim: #8b949e; --accent: #58a6ff;
    --user-bg: #1c2333; --bot-bg: #0d1117;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    background: var(--bg); color: var(--text);
    height: 100vh; display: flex; flex-direction: column;
  }

  .header {
    background: var(--surface); border-bottom: 1px solid var(--border);
    padding: 12px 20px; display: flex; align-items: center; gap: 16px;
    flex-shrink: 0;
  }
  .header h1 { font-size: 18px; font-weight: 600; }
  .header .meta { font-size: 12px; color: var(--text-dim); }
  .header .step-badge {
    background: #1f6feb33; color: var(--accent); padding: 2px 10px;
    border-radius: 12px; font-size: 12px; font-weight: 500;
  }
  .header .model-badge {
    background: #da363333; color: #f85149; padding: 2px 10px;
    border-radius: 12px; font-size: 12px; font-weight: 500;
  }
  .header .byte-badge {
    background: #23863633; color: #3fb950; padding: 2px 10px;
    border-radius: 12px; font-size: 12px; font-weight: 500;
  }

  .chat-container {
    flex: 1; overflow-y: auto; padding: 20px;
    display: flex; flex-direction: column; gap: 16px;
  }
  .message {
    max-width: 85%; padding: 12px 16px; border-radius: 12px;
    line-height: 1.6; white-space: pre-wrap; word-break: break-word;
    font-size: 14px;
  }
  .message.user {
    align-self: flex-end; background: var(--user-bg);
    border: 1px solid var(--border);
  }
  .message.bot {
    align-self: flex-start; background: var(--bot-bg);
    border: 1px solid var(--border);
  }
  .message .label {
    font-size: 11px; color: var(--text-dim); margin-bottom: 4px;
    text-transform: uppercase; letter-spacing: 0.5px;
  }

  .blade-bar {
    display: flex; gap: 3px; margin-top: 8px; align-items: flex-end;
    height: 32px;
  }
  .blade-bar .blade {
    flex: 1; border-radius: 2px 2px 0 0; min-width: 0;
    transition: height 0.15s ease;
  }

  .input-area {
    background: var(--surface); border-top: 1px solid var(--border);
    padding: 16px 20px; flex-shrink: 0;
  }
  .input-row { display: flex; gap: 10px; max-width: 900px; margin: 0 auto; }
  .input-row textarea {
    flex: 1; background: var(--bg); color: var(--text);
    border: 1px solid var(--border); border-radius: 8px;
    padding: 10px 14px; font-size: 14px; font-family: inherit;
    resize: none; outline: none; min-height: 44px; max-height: 120px;
  }
  .input-row textarea:focus { border-color: var(--accent); }
  .input-row button {
    background: var(--accent); color: #fff; border: none;
    border-radius: 8px; padding: 0 20px; font-size: 14px;
    cursor: pointer; font-weight: 500; white-space: nowrap;
  }
  .input-row button:hover { background: #4393e6; }
  .input-row button:disabled { opacity: 0.4; cursor: not-allowed; }

  .settings-toggle {
    background: none; color: var(--text-dim); border: 1px solid var(--border);
    border-radius: 6px; padding: 4px 10px; cursor: pointer; font-size: 12px;
  }
  .settings-panel {
    display: none; padding: 8px 20px; background: var(--surface);
    border-top: 1px solid var(--border);
  }
  .settings-panel.open { display: flex; gap: 20px; flex-wrap: wrap; }
  .setting { display: flex; flex-direction: column; gap: 2px; }
  .setting label { font-size: 11px; color: var(--text-dim); }
  .setting input {
    background: var(--bg); color: var(--text); border: 1px solid var(--border);
    border-radius: 4px; padding: 4px 8px; width: 80px; font-size: 13px;
  }

  .chat-container::-webkit-scrollbar { width: 6px; }
  .chat-container::-webkit-scrollbar-track { background: transparent; }
  .chat-container::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }

  .generating-indicator {
    display: inline-block; width: 6px; height: 14px;
    background: var(--accent); animation: blink 0.8s infinite;
    vertical-align: text-bottom; margin-left: 1px;
  }
  @keyframes blink { 0%,100% { opacity: 1; } 50% { opacity: 0.2; } }
  .token-counter { font-size: 11px; color: var(--text-dim); margin-top: 4px; text-align: right; }
</style>
</head>
<body>

<div class="header">
  <h1>HLM-v9 Chat</h1>
  <span class="step-badge" id="stepBadge">loading...</span>
  <span class="model-badge" id="paramBadge"></span>
  <span class="byte-badge">byte-level</span>
  <span class="meta" id="modelMeta"></span>
  <div style="flex:1"></div>
  <button class="settings-toggle" onclick="toggleSettings()">Settings</button>
</div>

<div class="settings-panel" id="settingsPanel">
  <div class="setting">
    <label>Temperature</label>
    <input type="number" id="temperature" value="0.8" step="0.05" min="0" max="2">
  </div>
  <div class="setting">
    <label>Max Bytes</label>
    <input type="number" id="maxBytes" value="512" step="64" min="1" max="2048">
  </div>
  <div class="setting">
    <label>Top-K</label>
    <input type="number" id="topK" value="40" step="5" min="0" max="256">
  </div>
  <div class="setting">
    <label>Top-P</label>
    <input type="number" id="topP" value="0.9" step="0.05" min="0" max="1">
  </div>
  <div class="setting">
    <label>Rep. Penalty</label>
    <input type="number" id="repPenalty" value="1.1" step="0.05" min="1" max="2">
  </div>
</div>

<div class="chat-container" id="chat"></div>

<div class="input-area">
  <div class="input-row">
    <textarea id="userInput" rows="1" placeholder="Type a message (text completion, not chat)..."
      onkeydown="if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send();}"></textarea>
    <button id="sendBtn" onclick="send()">Send</button>
  </div>
</div>

<script>
const chat = document.getElementById('chat');
const input = document.getElementById('userInput');
const sendBtn = document.getElementById('sendBtn');
const bladeNames = ['temporal','narrative','causation','affect','wisdom','ecology','relations','epistemics'];
const bladeColors = ['#eab308','#f97316','#ef4444','#ec4899','#a855f7','#22c55e','#6366f1','#06b6d4'];

input.addEventListener('input', () => {
  input.style.height = 'auto';
  input.style.height = Math.min(input.scrollHeight, 120) + 'px';
});

fetch('/api/info').then(r=>r.json()).then(info => {
  document.getElementById('stepBadge').textContent = 'Step ' + info.step;
  document.getElementById('paramBadge').textContent = info.params;
  document.getElementById('modelMeta').textContent =
    info.device + ' | ctx ' + info.max_seq_len + ' bytes | ' +
    info.n_blocks + ' blocks | loss ' + (info.loss || '?');
});

function toggleSettings() {
  document.getElementById('settingsPanel').classList.toggle('open');
}

function makeBladeBar(acts) {
  if (!acts) return '';
  const max = Math.max(...acts.map(Math.abs), 0.001);
  let html = '<div class="blade-bar">';
  for (let i = 0; i < 8; i++) {
    const h = Math.max(2, (Math.abs(acts[i]) / max) * 28);
    html += `<div class="blade" style="height:${h}px;background:${bladeColors[i]}"
      title="${bladeNames[i]}: ${(acts[i]*100).toFixed(1)}%"></div>`;
  }
  html += '</div>';
  html += '<div style="display:flex;gap:3px">';
  for (let i = 0; i < 8; i++) {
    html += `<div style="flex:1;font-size:7px;color:#8b949e;text-align:center">${bladeNames[i].slice(0,4)}</div>`;
  }
  html += '</div>';
  return html;
}

function scrollToBottom() { chat.scrollTop = chat.scrollHeight; }

let generating = false;

async function send() {
  const text = input.value.trim();
  if (!text || generating) return;

  const userDiv = document.createElement('div');
  userDiv.className = 'message user';
  userDiv.innerHTML = '<div class="label">You</div>' + escapeHtml(text);
  chat.appendChild(userDiv);
  input.value = '';
  input.style.height = 'auto';
  scrollToBottom();

  const botDiv = document.createElement('div');
  botDiv.className = 'message bot';
  botDiv.innerHTML = '<div class="label">HLM-v9</div><span id="botText"></span><span class="generating-indicator"></span>';
  chat.appendChild(botDiv);
  scrollToBottom();

  generating = true;
  sendBtn.disabled = true;

  const params = {
    prompt: text,
    max_new_bytes: parseInt(document.getElementById('maxBytes').value),
    temperature: parseFloat(document.getElementById('temperature').value),
    top_k: parseInt(document.getElementById('topK').value),
    top_p: parseFloat(document.getElementById('topP').value),
    repetition_penalty: parseFloat(document.getElementById('repPenalty').value),
  };

  let byteCount = 0;

  try {
    const resp = await fetch('/api/generate', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify(params),
    });

    const reader = resp.body.getReader();
    const decoder = new TextDecoder();
    let fullText = '';
    let lastBlades = null;
    let buffer = '';

    while (true) {
      const {value, done} = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, {stream: true});

      const lines = buffer.split('\n');
      buffer = lines.pop();

      for (const line of lines) {
        if (line.startsWith('data: ')) {
          const data = line.slice(6);
          if (data === '[DONE]') continue;
          try {
            const obj = JSON.parse(data);
            if (obj.text) {
              fullText += obj.text;
              byteCount += obj.n_bytes || 1;
              const textSpan = botDiv.querySelector('#botText');
              if (textSpan) textSpan.textContent = fullText;
              scrollToBottom();
            }
            if (obj.blades) lastBlades = obj.blades;
          } catch(e) {}
        }
      }
    }

    const cursor = botDiv.querySelector('.generating-indicator');
    if (cursor) cursor.remove();
    const textSpan = botDiv.querySelector('#botText');
    if (textSpan) textSpan.removeAttribute('id');
    if (lastBlades) {
      botDiv.insertAdjacentHTML('beforeend', makeBladeBar(lastBlades));
    }
    botDiv.insertAdjacentHTML('beforeend',
      `<div class="token-counter">${byteCount} bytes</div>`);

  } catch(err) {
    botDiv.innerHTML += '<br><span style="color:#f85149">Error: ' + escapeHtml(err.message) + '</span>';
  }

  generating = false;
  sendBtn.disabled = false;
  scrollToBottom();
  input.focus();
}

function escapeHtml(s) {
  const d = document.createElement('div');
  d.textContent = s;
  return d.innerHTML;
}

input.focus();
</script>
</body>
</html>"""


# ── Routes ───────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return HTML_PAGE


@app.route("/api/info")
def info():
    n_params = sum(p.numel() for p in MODEL.parameters())
    if n_params >= 1e9:
        params_str = f"{n_params / 1e9:.1f}B"
    else:
        params_str = f"{n_params / 1e6:.0f}M"
    return jsonify({
        "step": STEP,
        "params": params_str,
        "device": str(DEVICE),
        "max_seq_len": MODEL.max_seq_len,
        "n_blocks": MODEL.n_blocks,
        "d_model": MODEL.d_model,
        "loss": CONFIG.get("loss", None),
        "model_type": "hlm_v9",
    })


@app.route("/api/generate", methods=["POST"])
def api_generate():
    data = request.json
    prompt = data.get("prompt", "")
    if not prompt:
        return jsonify({"error": "empty prompt"}), 400

    max_new_bytes = data.get("max_new_bytes", 512)
    temperature = data.get("temperature", 0.8)
    top_k = data.get("top_k", 40)
    top_p = data.get("top_p", 0.9)
    rep_penalty = data.get("repetition_penalty", 1.1)

    def event_stream():
        byte_count = 0
        last_blade_check = 0
        blade_interval = 32  # Get blade profile every N bytes

        for text_chunk, blades in generate_stream(
            prompt, max_new_bytes, temperature, top_k, top_p, rep_penalty
        ):
            n_bytes = len(text_chunk.encode("utf-8"))
            byte_count += n_bytes
            payload = {"text": text_chunk, "n_bytes": n_bytes}

            # Periodically get blade profile (expensive, don't do every byte)
            if byte_count - last_blade_check >= blade_interval:
                prompt_bytes = list(prompt.encode("utf-8"))
                # We can't easily get blade profile mid-stream without
                # extra forward pass, so we do it at the end via /api/blades
                last_blade_check = byte_count

            if blades:
                payload["blades"] = blades
            yield f"data: {json.dumps(payload)}\n\n"
        yield "data: [DONE]\n\n"

    return Response(event_stream(), mimetype="text/event-stream")


@app.route("/api/blades", methods=["POST"])
def api_blades():
    """Get blade activation profile for a text."""
    data = request.json
    text = data.get("text", "")
    if not text:
        return jsonify({"error": "empty text"}), 400

    byte_seq = list(text.encode("utf-8"))[-MODEL.max_seq_len:]
    input_tensor = torch.tensor([byte_seq], dtype=torch.long, device=DEVICE)
    blades = get_blade_profile(input_tensor)
    return jsonify({"blades": blades, "blade_names": BLADE_SEMANTIC})


# ── Main ─────────────────────────────────────────────────────────────────

def main():
    global MODEL, CONFIG, DEVICE, STEP

    p = argparse.ArgumentParser(description="HLM-v9 Multiscale Chat Interface")
    p.add_argument("--checkpoint", required=True, help="Path to .pt checkpoint")
    p.add_argument("--device", default=None, help="Device (default: cuda if available)")
    p.add_argument("--port", type=int, default=7860)
    p.add_argument("--host", default="127.0.0.1")
    args = p.parse_args()

    if args.device is None:
        DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        DEVICE = args.device

    MODEL, CONFIG, STEP = load_model(args.checkpoint, DEVICE)

    log.info(f"Starting chat server on http://{args.host}:{args.port}")
    import webbrowser
    webbrowser.open(f"http://{args.host}:{args.port}")
    app.run(host=args.host, port=args.port, debug=False, threaded=True)


if __name__ == "__main__":
    main()
